export const events = [
  {
    id: 0,
    name: "Evento 0",
    capacity: 20,
    description: "an Empty event",
    organizer: "Dios",
    status: "Disponible",
    date: "17/Ago/2020 09:30am",
    maxCapacity: 31,
  },
  {
    id: 1,
    name: "Evento 1",
    capacity: 20,
    description: "an Empty event",
    organizer: "Dios",
    status: "Disponible",
    date: "17/Ago/2020 09:30am",
    maxCapacity: 31,
  },
  {
    id: 2,
    name: "Evento 2",
    capacity: 20,
    description: "an Empty event",
    organizer: "Dios",
    status: "Disponible",
    date: "17/Ago/2020 09:30am",
    maxCapacity: 31,
  },
  {
    id: 2,
    name: "Evento 2",
    capacity: 20,
    description: "an Empty event",
    organizer: "Dios",
    status: "Disponible",
    date: "17/Ago/2020 09:30am",
    maxCapacity: 31,
  },
  {
    id: 2,
    name: "Evento 2",
    capacity: 20,
    description: "an Empty event",
    organizer: "Dios",
    status: "Disponible",
    date: "17/Ago/2020 09:30am",
    maxCapacity: 31,
  },
];
